vich_uploader:
    db_driver: orm # or mongodb or phpcr

    mappings:
      animal_image:
        uri_prefix: /uploads/animal
        upload_destination: '%kernel.project_dir%/public/uploads/animal'
        namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

      activity_image:
        uri_prefix: /uploads/activity
        upload_destination: '%kernel.project_dir%/public/uploads/activity'
        namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
